export default {
  Any: "any",
  English: "en",
  Español: "es",
  Português: "pt",
  Deutsch: "de",
  한국어: "ko",
  русский: "ru",
  français: "fr",
  Italiano: "it",
  Türkçe: "tr",
  日本語: "ja",
  中文: "zh",
  "język polski": "pl",
  العربية: "ar",
  čeština: "cs",
  magyar: "hu",
  Nederlands: "nl",
  suomi: "fi",
  Svenska: "sv",
  ไทย: "th",
  dansk: "da",
  ελληνικά: "el",
  Norsk: "no",
  "български език": "bg",
  Română: "ro",
  Slovenčina: "sk",
  "Bahasa Indonesia": "id",
  Українська: "uk",
  "Wikang Tagalog": "tl",
  català: "ca",
  "Tiếng Việt": "vi",
  हिन्दी: "hi",
  "Bahasa Melayu": "ms",
};
